/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Владелец: предстоящие встречи (start_time в будущем), по возрастанию времени, keyset-пагинация. Cursor отражает срез на момент запроса; при конкурентных изменениях возможны дубли/пропуски. */
        get: operations["OwnerBookingsApi_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Владелец: отмена брони; освободившийся слот возвращается в доступные. */
        delete: operations["OwnerBookingsApi_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Гость: список типов событий, упорядочен по дате создания (created_at) по возрастанию. Тот же список используется в админке владельца. */
        get: operations["PublicEventTypesApi_list"];
        put?: never;
        /** @description Владелец: создать тип события. */
        post: operations["OwnerEventTypesApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Владелец: удалить тип события. 409, если есть брони. */
        delete: operations["OwnerEventTypesApi_delete"];
        options?: never;
        head?: never;
        /** @description Владелец: изменить тип события. Правка длительности не влияет на существующие брони (снимок в брони). */
        patch: operations["OwnerEventTypesApi_update"];
        trace?: never;
    };
    "/event-types/{id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Гость: создать бронь. start_time — старт свободного слота из /slots, иначе 400; конкурентная занятость слота — 409. end_time рассчитывается от текущей длительности типа (снимок на момент брони). */
        post: operations["PublicBookingApi_book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Гость: свободные слоты на окно [сегодня, сегодня+14) в TZ зрителя. tz — IANA-идентификатор; сетка стартов :00/:15/:30/:45; конец слота может выходить за окно. */
        get: operations["PublicEventTypesApi_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminBooking: {
            event_type_title: string;
        } & components["schemas"]["Booking"];
        /** @enum {string} */
        ApiVersions: "1.0.0";
        Booking: {
            id: components["schemas"]["Uuid"];
            event_type_id: components["schemas"]["Uuid"];
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            /** Format: int32 */
            duration_minutes: number;
            guest_name: string;
            /** Format: email */
            guest_email: string;
        };
        BookingConfirmation: {
            event_type_title: string;
        } & components["schemas"]["Booking"];
        BookingCreate: {
            guest_name: string;
            /** Format: email */
            guest_email: string;
            /** Format: date-time */
            start_time: string;
        };
        BookingPage: {
            items: components["schemas"]["AdminBooking"][];
            next_cursor?: string;
        };
        ErrorBody: {
            message: string;
        };
        EventType: {
            id: components["schemas"]["Uuid"];
            title: string;
            description: string | null;
            /** Format: int32 */
            duration_minutes: number;
        };
        EventTypeCreate: {
            title: string;
            description?: string;
            /** Format: int32 */
            duration_minutes: number;
        };
        EventTypeUpdate: {
            title?: string;
            description?: string | null;
            /** Format: int32 */
            duration_minutes?: number;
        };
        Slot: {
            /** Format: date-time */
            start: string;
            /** Format: int32 */
            duration_minutes: number;
        };
        SlotsResponse: {
            window: {
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
            };
            slots: components["schemas"]["Slot"][];
        };
        /** Format: uuid */
        Uuid: string;
        ValidationBody: {
            errors: {
                [key: string]: string[];
            };
        } & components["schemas"]["ErrorBody"];
    };
    responses: never;
    parameters: {
        "BookingListParams.cursor": string;
        "BookingListParams.limit": number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    OwnerBookingsApi_list: {
        parameters: {
            query?: {
                limit?: components["parameters"]["BookingListParams.limit"];
                cursor?: components["parameters"]["BookingListParams.cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBody"];
                };
            };
        };
    };
    OwnerBookingsApi_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    PublicEventTypesApi_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    OwnerEventTypesApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBody"];
                };
            };
        };
    };
    OwnerEventTypesApi_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    OwnerEventTypesApi_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    PublicBookingApi_book: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingConfirmation"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    PublicEventTypesApi_slots: {
        parameters: {
            query: {
                /** @description IANA-идентификатор часового пояса зрителя, например Europe/Moscow. */
                tz: string;
            };
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
